### ISSUE TITLE
Add Zuggtmoy-enhanced Myconids to OotA bestiary

### ISSUE THREAD

**Issue by TheGiddyLimit** [TheGiddyLimit/TheGiddyLimit.github.io#118]
"An idea could also be to add, as variant features (instead of mixing them with default ones),
the enhancements that myconids (adults and sovereign) receive from Zuggtmoy (OotA page 228)."

**Comment by Temp345** [comment]
I can do that, if you want. In fact, I have it ready, but
I'll wait for your answer to the other issue I've opened
(checking if I can heavily modify the bestiary without
bothering other works in progress).

Should I keep the formula to calculate the DC of those abilities saving throws?
There's a (remote) chance that other kind of myconids could be added in the future,
thought these features clearly state that are intended for adults and sovereign only. Uhm...

> Caustic Spores (1/ Day). The myconid releases spores in a 30-foot cone. Each creature inside the cone must succeed on a **DC 11** Dexterity saving throw or take 1d6 acid damage at the start of each of the myconid's turns. A creature can repeat the saving throw at the end of its turn, ending the effect on itself on a success. **The save DC is 8 + the myconid's Constitution modifier + the myconid's proficiency bonus**.

The "DC 11" wasn't in the original text (since it could be 11 or 12, if used respectively to the Myconid adult or Myconid Sovereign).

I've used the "variant" property used also by some drow.
It seems to me that keeping the optional/variant features separated from the main ones
makes the stat block more readable (giants have them all mixed up and I don't like that).

**Comment by Temp345** [comment]
Slightly unrelated question. For some summoning features, like drow priestess of Lolth,
the success is related to a percentage chance. Does it make sense to add a "roller"?
Can you think, off the top of your head, of the format to use? (otherwise I'll make my homework)

> The drow attempts to magically summon a {@creature yochlol} with a 30 percent chance of success.

How would you do it? Something like "30 (1d100) percent chance" or there's a better way to do it?

**Comment by TheGiddyLimit** [comment]
Adding them as variants seems good. Same with the SKT giant variants, if you wish! Although thinking about it, there ought to be a note about where the additional info comes from; would be good to add something similar to the `additionalSources` found in a few items/deities:
```json
"source": "PHB",
"page": 154,
"additionalSources": [
	{
		"source": "XGE",
		"page": 81
	}
]
```

There's no code to actually output that yet, but if you add it to the data, I'll make it render.

Having not read/played OotA, `Zuggtmoy Enhancement` sounds fine. So long as it's kept consistent and inoffensive (don't call it `Dark Empowerment` or something cutesy) then it's all good.

As for adding rollers to percentage changes, not sure. Might warrant a new tag, {@chance [%]}, which would output "success" or "failure" in the roller output when clicked? Making it a clickable roller doesn't feel good enough. Again, if you want to add that to the data (e.g. `{@chance 30}` for the Drow example) I'll make it render.

**Comment by Temp345** [comment]
I think we could use the newly added
{@dice 1d100|50 percent chance|50% summoning chance"

Is it ok to use the "%" character?

**Comment by TheGiddyLimit** [comment]
As I said, I don't want to do that. It's not appropriate. You'd do it with a dice roll at a table, sure, but we have the luxury of being able to say "success" or "failure" instead of having you look at the number you rolled and the number you had to beat (which in itself requires some decision making; are you trying to roll over 50, or under?). New tag, plsthx. 

It can use the same syntax; `{@chance 50|50 percent chance|50% summoning chance}`, but when you click it, it'll tell you if it succeeded or failed, instead of giving you the raw number (although that can be in the output, too, why not).

**Comment by TheGiddyLimit** [comment]
Alright, `additionalSources` will work on Bestiary data now, too.

**Comment by Temp345** [comment]
The MM's bestiary is ready. You tell me if I should use @chance or not, it's the same for me.

I can't promise I'll do the whole bestiary (certainly I won't do third party stuff).

**Comment by TheGiddyLimit** [comment]
Go for it, I'll fix up the code side tonight, and merge in any relevant PRs after. This repo is the "unofficial" version of 5etools anyway, so if things are a little crooked, it's no issue.

Anything you do is highly appreciated, it's all progress!

**Comment by Temp345** [comment]
Don't mention it. Last question and confirmation then I'll leave you alone:
is it safe to use directly the "%" character or is it better to use the... uhm.. escape thing...
like the one for apostrophes?

**Comment by TheGiddyLimit** [comment]
Anything that gets turned into a URL could have problems with that (I've never tried, but I assume it wouldn't go well), but should be safe to use in dice/chance/clickable rollers.

**Comment by TheGiddyLimit** [comment]
Reworked the format some, see 4d785d74653e7d298689a06061c118d8d4a4edc0. Source can now be included in the variant itself, and will display at the bottom of the variant box. Makes it clear where the info came from, without having to add `From OotA` etc in the titles.
