### ISSUE TITLE
A few questions/ideas

### ISSUE THREAD

**Issue by Temp345** [TheGiddyLimit/TheGiddyLimit.github.io#129]
Shouldn't demonic boons be grouped together with devil cults?
Aren't they are supposed to be used for NPCs/monsters only (as a rule of thumb at least)?
While the other rewards (blessings, boons and charms) could go either way
(but I guess they are primarily designed for PC).
Also, shouldn't the **Other Rewards** page be under "DM Tools" instead of "References"?
Not that this is a big deal, I guess there are also good reasons for it to be where it is.

I'm not sure about this, I looked online but found no clear answer.
I was thinking about some items/spells that link to the scrying spell.
For example the [amulet of proof against detection](https://thegiddylimit.github.io/items.html#amulet%20of%20proof%20against%20detection%20and%20location_dmg).
Are we sure that the "scrying sensors" described in its text only relate to the [scrying](https://thegiddylimit.github.io/spells.html#scrying_phb) spell?
Are there other divination spells (that target a creature specifically, because those with
a range of "self" or "range" shouldn't count) that could do that?
Should it work also against [clairvoyance](https://thegiddylimit.github.io/spells.html#clairvoyance_phb)
(which also mentions a "sensor") and maybe also arcane eye and other spells?
See also the [private sanctum](https://thegiddylimit.github.io/spells.html#mordenkainen's%20private%20sanctum_phb) about blocking sensors.
The target of the spell probably is relevant, i.e. if it targets directly a creature or self or a point.
EDIT: using the spell filter to check only divination magic and...
EDIT2: I'm not totally convinced but it seems it's only related to the scrying spell. Sorry for the rambling.

This could be a bit of a stretch. Check the transmutation wizard class.
In the [Shapechanger](https://thegiddylimit.github.io/classes.html#wizard_phb,sub:school%20of%20transmutation~phb,hideclassfs:true,f:arcane%20tradition%20feature9) option, what if we turned "_a beast whose challenge rating is 1 or lower_"
into a link to the bestiary, filtered accordingly? Does the @filter thingy already support that?
If that's the only place where such a link would be used then maybe it's not worth the effort
(if it has to be specifically implemented), but maybe something like this can be useful also
for Druids or other features and spells (conjure*)?
Related: if and when you can, can you put an example in the renderer demo about how the
@filter can be used (not listing exhaustively all the options, just to get an idea how it can be used)?

Is the updating of the bestiary done? (to support cool shit)
Can I update creatures with the Special Equipment "trait" to add links to the related items?
Or would that still conflicts with or bother other works in progress?

**Comment by TheGiddyLimit** [comment]
- Right enough, Demonic Boons don't exactly fit where they are. Wasn't me that added them tbh, never looked closely at it. Probably should be split into their own page, and moved under `DM Tools`, as much as it pains me to clutter that even further.
- As you rightly pointed out, most of the `Other Rewards` are intended for PCs, hence why they're under `References` instead of `DM Tools`. 

- I agree that linking the Scrying spell in the text "...magical scrying sensors..." is not necessarily correct; have removed those links. It'll be from find-replacing "scrying" to make the links, is all.

- Have added support for @filter on the Bestiary page, and added the tag to the example you provided (Transmutation level 10 feature). It has to be added on a per-page basis; previously only Races and Spells supported it. It's pretty generic/easy to add to other pages as required, there merely hadn't been a need, as nobody had pointed out these potential use-cases. There's no example in the renderer demo because it relies on things that aren't externally visible, i.e. you need to look at how the filters are coded for the given page. For example, the spell schools being `school=D` for Divination is not exactly obvious -- for example, can you guess what Evocation is? Because it's not `school=E` (that's Enchantment, of course). It's intended for internal magic-working, really; I felt adding it to the demo would raise more questions than it answered. You're probably right, though, some simple examples, with a note of "if you want to know how to do X, read the code, or ask" would be helpful. I'll add that soon.

- The Bestiary does indeed support cool shit, in general, anywhere you see `entries: [...]` does. The man who was working on it vanished, so you can probably crack at. If he comes back and gets upset, that's his problem, not yours :wink: One note, if the special equipment is part of a `Variant: ...`, add it using the new `variant` stuff; see MM's Satyr or Troll for examples. Converting the rest is somewhere deep in the to-do list, which is only getting longer, unfortunately. I've not had much free time of late, and have shamefully been dedicating less of it to 5etools (a minor vidya renaissance happening in my group of compardres, although it'll surely die out soon enough).

**Comment by Temp345** [comment]
> Demonic Boons [CUT] Probably should be split into their own page, and moved under DM Tools, as much as it pains me to clutter that even further.

There are too few, IMO, to warrant their own page. If it was me, I'll group them together with the
devil cults since they are close enough as far as their theme goes (IIRC), maybe renaming the
page "Cults and Boons" or something. Anyway, not a big deal.

> As you rightly pointed out, most of the Other Rewards are intended for PCs, hence why they're under References instead of DM Tools.

I though it was the DM that decided if/when reward a player with one of those, it's not like
players can choose what they get, or can they (haven't read those sections in a while)?
Not really important at the end of the day.

I agree about @filter's format and options being a bit above the average user.

Thanks!

**Comment by TheGiddyLimit** [comment]
Yeah, might as well move them in there. Would nicely package up that crappy UA content, at least. Will take a bit of fiddling; I'll do it later.

Rewards are entirely up to the DM, sure, but you'd still want a reference to read what it does, as a player. That's the basic intention of the split; anything a player would have on their character sheet/need to know should be in `References`.

**Comment by Temp345** [comment]
Gotcha. Makes sense.
