### ISSUE TITLE
Adult Red Dragon has 2 lair actions

### ISSUE THREAD

**Issue by Konahrik13** [TheGiddyLimit/TheGiddyLimit.github.io#15]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request:

Issue: There's the old one after Fire Breath and the updated one is below it. I'd wager get rid of the old one.

Page(s) affected: Adult Red Dragon in the Bestiary

Reproduction steps:

Additional information: I remember you from astranauta's 5etools. Thank you for bringing it back and continuing to work on it.

Browser (Chromium, Firefox, Edge, etc):

Platform (Windows, iOS, Android, etc):

**Comment by TheGiddyLimit** [comment]
Fixed in #18.

Sorry I didn't get to this sooner, GitHub decided to stop sending me email notifications, for whatever reason. Somebody else kindly took care of it, though, so it's not all bad.

Thanks for the kind words! The whole gang is still together (mostly, one dude dipped, I guess doesn't want to get into any legal trouble) so I can't take all the credit.
