### ISSUE TITLE
Request: Link to creature list instead of upload.

### ISSUE THREAD

**Issue by MattParsons118** [TheGiddyLimit/TheGiddyLimit.github.io#151]
I've been using these tools for a couple of weeks now and so far my only complaint (and it's a pretty minor one) is that I can't create a link to open a creature list. My notes are digital, so if I could embed a link directly to the list of stat blocks I'll need for an encounter, it would be awesome. Thanks!

**Comment by TheGiddyLimit** [comment]
Bashed it out during a coffee break/meeting so expect it to not work, but you should now be able to shift-click the download button and get the link. See if it works?

**Comment by MattParsons118** [comment]
It gives the link, but loading the link doesn't change anything. It still loads the list from cookies. Maybe it's being overwritten?

**Comment by MattParsons118** [comment]
`json` isn't defined in `setFromSubHashes`, utils.js line 1758.

**Comment by TheGiddyLimit** [comment]
True enough. Moved some code around to appease the linter, never checked it still worked afterwards. Will fix.

**Comment by MattParsons118** [comment]
It works perfectly. You're awesome.

**Comment by MattParsons118** [comment]
It stopped working.

**Comment by TheGiddyLimit** [comment]
Seems to be OK for me. What's the problem, exactly?

**Comment by TheGiddyLimit** [comment]
That link doesn't seem to have any creature data, it's only filters. Are you clicking the "Magnet" button instead of SHIFT-clicking the "Download" button? Either way, something's very off.

Chrome should be perfectly fine, that's what I develop/test on.

Here's what I get with 11 Spiny lads and 1 Fiendlock: [link](https://thegiddylimit.github.io/bestiary.html#spined%20devil_mm,sublistselected:%7B%22items%22%3A%5B%7B%22h%22%3A%22spined%2520devil_mm%22%2C%22c%22%3A%2211%22%7D%2C%7B%22h%22%3A%22warlock%2520of%2520the%2520fiend_vgm%22%2C%22c%22%3A%221%22%7D%5D%2C%22sources%22%3A%5B%22mm%22%2C%22vgm%22%5D%7D).

**Comment by MattParsons118** [comment]
Yeah, sorry, I was clicking "get link." Easy mistake, lol.
