### ISSUE TITLE
Add switch from mouse over to link on click / touch device simple support

### ISSUE THREAD

**Issue by thaihugo** [TheGiddyLimit/TheGiddyLimit.github.io#185]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Feature request

Issue: on a touch device (IOS, Android), most of the interface register touch as click. However, when viewing any monster in bestiary, for example going to the spell list, the mouse over preview display is more interesting to have as it allows for a quick view instead of loading a new full page in a new tab. It is not currently possible to have this for the moment.

A simple switch like the night mode switch would be appreciated here to change the clicking behavior for links and display a quick preview window to browse spells assigned to a monster for example.

Page(s) affected: any page with mouse over behavior, but bestiary.html would be a good compromise if it cannot be done everywhere.

Reproduction steps: go to this subpage : /bestiary.html#acererak_toa, click the knock spell, new page open instead of a preview pop up. 

Additional information: ideally, each items, spell, monster and any link would be previewed instead of linked in the recursive renderer window, and +x ability dices would keep their actual behavior. A button switch or a long click to “open in a new tab” would bring the old behavior

Browser (Chromium, Firefox, Edge, etc): Safari , Firefox, Chrome

Platform (Windows, iOS, Android, etc): IOS 11.3

Thanks In advance for your time and help

**Comment by TheGiddyLimit** [comment]
An interesting thought, to be sure. I don't actually own a touchscreen device with high enough resolution to allow the hover window to render, so I'll have to table this for now -- doubly so as we're in the middle of a UI redesign, and I'm not allowed to add any more buttons to things (once the redesign is done, though, there should be plenty space for sticking buttons in menus, instead of the current option, which is to clutter an already disgustingly overburdened header).

Out of interest, how does D&D Beyond handle it? E.g. [Druid](https://www.dndbeyond.com/monsters/druid), which is SRD, so should be accessible.

**Comment by thaihugo** [comment]
I’ve been testing the link provided. On iOS, it is the expected behavior. It doesn’t need a switch button: on a tap, it open a preview window, and switch spell when tapping other links. On a long press, it gives me a standard OS menu to open in a new tab. I guess there is even an iOS detection in the CSS so that wouldn’t need a switch button at all.
If this way could be implemented, that would certainly be a great feature for us on mobile.
On your interface, the third tab between the minus sign to remove a monster from list and the magnet sign to create a full link also displays a proper preview window with an x to close it on my device.

**Comment by thaihugo** [comment]
May I bump a bit this request by saying this function is already there for some dot underlined links. In the sample below, the dotted underline is working as I would like to, and the blue link is loading a new page. I don’t know if this can become more commonplace for spell descriptions for example?

![b0abe008-3cb7-4e48-81fa-6e01da19772a](https://user-images.githubusercontent.com/17780673/52909207-9ca96400-32bf-11e9-9c69-65a670933e26.jpeg)

**Comment by TheGiddyLimit** [comment]
The functionality "exists" for both; your browser just prefers switching page to showing the hover box (as it should). You may be able to see the hover window if you long-press a link and cancel the context menu.

Regardless, since it seems the 2.0 redesign has fallen off the radar for the time being, I've hacked something together for next release. If you tap a link, it should open the hover window. If you long-press, you can still e.g. open the link in a new tab.
