### ISSUE TITLE
Make search more useful

### ISSUE THREAD

**Issue by r0gu3Ag3n7** [TheGiddyLimit/TheGiddyLimit.github.io#253]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Both?  

Issue: Search could be far more useful, "Search Everywhere" doesn't actually.

Page(s) affected: All

Reproduction steps: For example, whether I am in the DM tools/Adventures/LMoP or ANYWHERE I cannot search for "Cragmaw".  Whether cragmaw hideout, or information about the goblins, this is a major term that should be searchable.  I compare to DND Beyond where search literally searches the body text.  

Additional information:  This would make these tools more useful.

Browser (Chromium, Firefox, Edge, etc): Any

Platform (Windows, iOS, Android, etc): Any

**Comment by TheGiddyLimit** [comment]
Sure; if you hover over the search bar, it tells you this.

I do agree, though. Problem is, it's not particularly viable--our search is entirely client-side (for infrastructure reasons and otherwise), so this would mean loading the entire content of the site (about 30MiB, and growing) for a user each time that user searched.

This might all change in the future, but for now, no plans. I'll certainly keep it in mind, though.

PS: You can press "F" when viewing the adventure to search in the adventure text.
