### ISSUE TITLE
Dart does not not have an ammunition resource

### ISSUE THREAD

**Issue by kcddagger** [TheGiddyLimit/TheGiddyLimit.github.io#339]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request: Bug

Issue: Adding Darts to a character sheet from the Plutonium Items collection does not make them Ammunition resources.  Clicking in Foundry to use Dart to attack shows an error message that stated that Dart could not be used, as an Ammunition as a resource had not been defined for it.

Page(s) affected: 

Reproduction steps:

1. Fresh install of FoundryVTT, and a brand new world with the Plutonium package loaded and activated.
2. Created a new character actor
3. Added 10 darts from the Plutonium Items Compendium
4. Clicked the Dice icon that shows on mouse-over of the dart weapon
5. Clicked attack in the Dart panel in the Chat Log
6. Got the error message mentioned in the Issue.
7. Removed the darts in the inventory
8. Opened up the PHB Items list and added 10 darts to the actor inventory
9. Repeated steps 4 & 5
10. Dart attack worked and properly subtracted the dart from the inventory
11. Removed the PHB Darts from the inventory
12. Opened the Plutonium Item Compendium and repeated steps 3-5
13. No error message and the attack worked as intended with inventory management tracking properly.

Additional information: All of the above was done in the FoundryVTT DM server software, no browser as I am setting up to host a game

Browser (Chromium, Firefox, Edge, etc): N/A

Platform (Windows, iOS, Android, etc): Windows 10, most current Feature Version.

**Comment by TheGiddyLimit** [comment]
Can't reproduce in current Plutonium (and since you did not provide your Plutonium, dnd5e, or Foundry version, this may be an issue), nor can I reproduce it in the 0.8.x candidate Plutonium. 

Dart ammo usage doesn't get set unless you're specifically importing (with the item importer) to an actor, so I don't see how this could occur anyway.

As an aside, this is not the place to report Plutonium issues. Please join our Discord and report them there, where the appropriate forms/help are available.
